SyneRBI/SyneRBI_VM

scripts/UPDATE.sh
update script uses SuperBuild to build SIRF in VM.
=> Superbuild

scripts/UPDATE.sh
Allows the user to update the VM. 
Fixes #28
=> creates buildVM only if not present

scripts/UPDATE.sh
removes cached SIRF, Gadgetron, ISMRMRD, STIR  URL and TAG.
uses mkdir -p rather than test.
Closes #31 
addresses https://github.com/CCPPETMR/CCPPETMR_VM/pull/29#pullrequestreview-67034267
=> Removes entries from cache

scripts/UPDATE.sh
=> Avoids multiple append of source sirfrc in bashrc

scripts/update_VGA.sh
=> Abort if VGA CD not found

scripts/UPDATE.sh
Closes #1
Prerequisites are already installed by https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/scripts/INSTALL_prerequisites_with_apt-get.sh
=> Build siemens_to_ismrmrd in the VM

scripts/update_VGA.sh
Try to mount on /media/cdrom as last resort. See #60.
=> Try /dev/sr0 for VGA

scripts/first_run.sh, vagrant/Vagrantfile
=> remove env variables and increase pointer size

scripts/first_run.sh
=> added comment for zerofill

scripts/INSTALL_prerequisites_with_apt-get.sh, scripts/UPDATE.sh, scripts/first_run.sh, vagrant/Vagrantfile
=> Install new packages

CHANGES.md, scripts/INSTALL_prerequisites_with_apt-get.sh, scripts/UPDATE.sh, scripts/update_VM_with_exercises.sh, vagrant/Vagrantfile
Currently the UPDATE.sh is not called at creation time as I wanted to test a few details of the VM I created before building SIRF.
=> Virtualbox ubuntu packages

scripts/UPDATE.sh
=> set USE_SYSTEM_BOOST to Off

scripts/UPDATE.sh, vagrant/Vagrantfile
This should resolve some issues with pip not being able to cache,
and is cleaner anyway
Closes #96
=> don't set HOME and run UPDATE as the user

scripts/INSTALL_prerequisites_with_apt-get.sh, scripts/UPDATE.sh
closes #100 
(merge, don't squash)
=> Port stir-VM changes to master

scripts/INSTALL_prerequisites_with_apt-get.sh
satisfies https://github.com/CCPPETMR/SIRF-SuperBuild/pull/154
=> add cython dependency

vagrant/Vagrantfile
=> forward ports for Gadgetron

scripts/first_run.sh
sets default ip and default notebook_dir for jupyter
see #123
=> updates the jupyter config

scripts/INSTALL_prerequisites_with_apt-get.sh
=> install linux kernel headers

documentation/Updating-VM-to-a-new-major-release.md, scripts/UPDATE.sh
fixes https://github.com/SyneRBI/SyneRBI_VM/issues/156
@johannesmayer did you say you'd be able to try this one?
=> option to install prerequisites

scripts/UPDATE.sh
=> git fetch before checking out SB branch

scripts/INSTALL_python_packages.sh
The undersampled reconstruction notebook needs this package but it's not installed in the current VM.
=> Added tqdm installation in python package update step

scripts/UPDATE.sh
=> add pet_rd tools

scripts/INSTALL_prerequisites_with_apt-get.sh
=> adds libdcmt-dev in Gadgetron apt prerequisites

scripts/UPDATE.sh
=> adds pull after fetch
